### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Afeihan** [suji0131/Advanced_Lane_Detection#1]
Thank you for your share of the source code, and when I run the script of line_fit_video.py，I meet this error：

[MoviePy] >>>> Building video project_out.mp4
[MoviePy] Writing video project_out.mp4
  0%|          | 0/3861 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/han/lane-detection/2-11-推荐advanced_lane_detection-master/line_fit_video.py", line 104, in <module>
    annotate_video('project.mp4', 'project_out.mp4')
  File "/home/han/lane-detection/2-11-推荐advanced_lane_detection-master/line_fit_video.py", line 99, in annotate_video
    annotated_video.write_videofile(output_file, audio=False)
  File "<decorator-gen-51>", line 2, in write_videofile
  File "/usr/local/lib/python3.5/dist-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-50>", line 2, in write_videofile
  File "/usr/local/lib/python3.5/dist-packages/moviepy/decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-49>", line 2, in write_videofile
  File "/usr/local/lib/python3.5/dist-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.5/dist-packages/moviepy/video/VideoClip.py", line 349, in write_videofile
    progress_bar=progress_bar)
  File "/usr/local/lib/python3.5/dist-packages/moviepy/video/io/ffmpeg_writer.py", line 209, in ffmpeg_write_video
    fps=fps, dtype="uint8"):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 833, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.5/dist-packages/moviepy/Clip.py", line 475, in generator
    frame = self.get_frame(t)
  File "<decorator-gen-14>", line 2, in get_frame
  File "/usr/local/lib/python3.5/dist-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/usr/local/lib/python3.5/dist-packages/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "/usr/local/lib/python3.5/dist-packages/moviepy/Clip.py", line 136, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "/usr/local/lib/python3.5/dist-packages/moviepy/video/VideoClip.py", line 533, in <lambda>
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "/home/han/lane-detection/2-11-推荐advanced_lane_detection-master/line_fit_video.py", line 65, in annotate_image
    left_fit = ret['left_fit']
TypeError: 'NoneType' object is not subscriptable
Process finished with exit code 1

I'm  looking forward your reply!

**Comment by Afeihan** [comment]
Is it because there is a demand for camera placement or the pixels of the vedio ?


7/5000

Camera pixel requirements
